name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    outputs:
      source_code: ${{ steps.filter.outputs.source_code }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            source_code:
              - "**/*.go"
              - "**/*.sql"
              - "go.mod"
              - "go.sum"
              - ".github/workflows/ci.yaml"

  ci:
    needs: changes
    if: ${{ needs.changes.outputs.source_code == 'true' }}
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Format check
        run: nix develop -c bash -c "make fmt && git diff --exit-code"

      - name: Check
        run: nix develop -c make check

      - name: Sql check
        run: nix develop -c make check-sql

      - name: Build
        run: nix develop -c make build

      - name: Test
        run: nix develop -c make test
